version: '3'
services:
  mysql:
    container_name: mysql
    build: ./mysql
    volumes:
      - mysql_volume:/var/lib/mysql
    env_file:
      - .env
    networks:
      - mynetwork
    restart: always
  wordpress:
    container_name: wordpress
    build: ./wordpress
    depends_on:
      - mysql
    volumes: 
      - wp_volume:/var/www/html
    env_file: .env
    networks:
      - mynetwork
    restart: always
  nginx:
    container_name: nginx
    build: ./nginx
    depends_on:
      - wordpress
    volumes:
      - wp_volume:/var/www/html
    ports:
      - "443:443"
    networks:
      - mynetwork
    restart: always
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    env_file: .env
    depends_on:
      - mysql
      - wordpress
    networks:
      - mynetwork
    ports:
      - "8080:80"
    restart: always
volumes:
  wp_volume:
    name: wp_volume
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/alboumed/data/wp_volume
  mysql_volume:
    name: mysql_volume
    driver: local
    driver_opts:
      type: 'none'
      o: bind
      device: /home/alboumed/data/mysql_volume
networks:
  mynetwork: